Repository OZ-Coding-School/oz_03_collabo-003-BE, pull requests merged in 2024-08, with the labels that each got.

#2 [문서 추가] PR 템플릿
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#3 [문서 업데이트] : Readme 제목 수정
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
Labels: documentation

#4 [문서 업데이트] Readme 제목 수정
  README.md
Labels: documentation

#8 [Feat] 일반 로그인/회원가입
  .github/workflows/python_formatter.yml
  LICENSE
  app/accounts/__init__.py
  app/accounts/admin.py
  app/accounts/apps.py
  app/accounts/forms.py
  app/accounts/managers.py
  app/accounts/middleware.py
  app/accounts/migrations/0001_initial.py
  app/accounts/migrations/0002_alter_refreshtoken_options_alter_user_options_and_more.py
  app/accounts/migrations/__init__.py
  app/accounts/models.py
  app/accounts/serializers.py
  app/accounts/templates/login.html
  app/accounts/templates/logout.html
  app/accounts/templates/signup.html
  app/accounts/tests.py
  app/accounts/urls.py
  app/accounts/views.py
  app/app/__init__.py
  app/app/asgi.py
  app/app/settings.py
  app/app/urls.py
  app/app/wsgi.py
  app/manage.py
  poetry.lock
  pyproject.toml
  requirements.txt
Labels: enhancement

#9 [기능추가] API Doc / Redoc&Swagger Update
  allthe/accounts/__init__.py
  allthe/accounts/admin.py
  allthe/accounts/apps.py
  allthe/accounts/forms.py
  allthe/accounts/managers.py
  allthe/accounts/middleware.py
  allthe/accounts/migrations/0001_initial.py
  allthe/accounts/migrations/__init__.py
  allthe/accounts/models.py
  allthe/accounts/serializers.py
  allthe/accounts/templates/login.html
  allthe/accounts/templates/logout.html
  allthe/accounts/templates/signup.html
  allthe/accounts/tests.py
  allthe/accounts/urls.py
  allthe/accounts/views.py
  allthe/allthe/__init__.py
  allthe/allthe/asgi.py
  allthe/allthe/settings.py
  allthe/allthe/urls.py
  allthe/allthe/wsgi.py
  allthe/manage.py
  app/accounts/apps.py
  app/accounts/migrations/0001_initial.py
  app/accounts/migrations/0002_alter_refreshtoken_options_alter_user_options_and_more.py
  app/app/settings.py
  app/app/urls.py
  requirements.txt
Labels: enhancement

#10 [FEATURE] 도커 파일 생성 및 ,RDS 연결
  .gitignore
  allthe/accounts/apps.py
  allthe/accounts/migrations/0001_initial.py
  allthe/accounts/views.py
  allthe/allthe/asgi.py
  allthe/allthe/settings.py
  allthe/allthe/urls.py
  allthe/allthe/wsgi.py
  allthe/manage.py
  docker-compose.yml
  dockerfile
  requirements.txt
Labels: enhancement

#11 [FEATURE] 장고 세팅
  allthe/accounts/migrations/0002_remove_user_provider_user_business_number_and_more.py
  allthe/accounts/migrations/0003_user_phone_number.py
  allthe/accounts/models.py
  allthe/admin_panel/__init__.py
  allthe/admin_panel/admin.py
  allthe/admin_panel/apps.py
  allthe/admin_panel/migrations/0001_initial.py
  allthe/admin_panel/migrations/__init__.py
  allthe/admin_panel/models.py
  allthe/admin_panel/tests.py
  allthe/admin_panel/views.py
  allthe/allthe/settings.py
  allthe/analysis/__init__.py
  allthe/analysis/admin.py
  allthe/analysis/apps.py
  allthe/analysis/migrations/0001_initial.py
  allthe/analysis/migrations/0002_initial.py
  allthe/analysis/migrations/__init__.py
  allthe/analysis/models.py
  allthe/analysis/tests.py
  allthe/analysis/views.py
  allthe/common/__init__.py
  allthe/common/admin.py
  allthe/common/apps.py
  allthe/common/decorators.py
  allthe/common/migrations/__init__.py
  allthe/common/models.py
  allthe/common/tests.py
  allthe/common/views.py
  allthe/contents/__init__.py
  allthe/contents/admin.py
  allthe/contents/apps.py
  allthe/contents/migrations/0001_initial.py
  allthe/contents/migrations/__init__.py
  allthe/contents/models.py
  allthe/contents/tests.py
  allthe/contents/views.py
  allthe/payments/__init__.py
  allthe/payments/admin.py
  allthe/payments/apps.py
  allthe/payments/migrations/0001_initial.py
  allthe/payments/migrations/__init__.py
  allthe/payments/models.py
  allthe/payments/tests.py
  allthe/payments/views.py
Labels: enhancement

#13 [기능추가] social_login
  allthe/accounts/urls.py
  allthe/accounts/views.py
  allthe/allthe/settings.py
  dockerfile
  poetry.lock
  pyproject.toml
  requirements.txt
Labels: enhancement

#14 [FEAT] CI 추가
  .github/workflows/django_server_test.yml
Labels: enhancement

#15 [FEAT] CD 설정
  .github/workflows/Django_CD.yml
  .github/workflows/Django_CI.yml
  deploy.sh
Labels: enhancement

#16 [Fix] CD Code2
  .github/workflows/Django_CD.yml
Labels: fix

#17 [Fix] CD Code3
  .github/workflows/Django_CD.yml
Labels: fix

#18 [Fix] CD오류 수정
  .github/workflows/Django_CD.yml
Labels: fix

#19 [Fix] CD Code5
  .github/workflows/Django_CD.yml
Labels: fix

#20 [Feature] CD Code Fix
  .github/workflows/Django_CD.yml
  deploy.sh
Labels: fix

#21 [Fix] CD Code8
  .github/workflows/Django_CD.yml
Labels: fix

#22 [Fix] CD Code Test
  .github/workflows/Django_CD.yml
Labels: fix

#23 [Fix] CD Code10
  .github/workflows/Django_CD.yml
Labels: fix

#24 [Fix] CD Code11
  .github/workflows/Django_CD.yml
Labels: fix

#25 [Fix] CD Code12
  .dockerignore
  .github/workflows/Django_CD.yml
Labels: fix

#26 [Fix] CI/CD Code13
  .github/workflows/Django_CD.yml
  .github/workflows/Django_CI.yml
Labels: fix

#27 [Fix] CI/CD Code14
  .github/workflows/Django_CD.yml
  .github/workflows/Django_CI.yml
  .github/workflows/Django_CICD.yml
  deploy.sh
Labels: fix

#28 [Fix] CI/CD Code18
  .github/workflows/Django_CICD.yml
  deploy.sh
Labels: fix

#29 [Fix] CI/CD Code19
  .github/workflows/Django_CICD.yml
  wait-for-it.sh
Labels: fix

#30 [Fix] CI/CD Code23
  .github/workflows/Django_CICD.yml
  docker-compose.yml
Labels: fix

#31 [Fix] CI/CD Code25
  .github/workflows/Django_CICD.yml
Labels: fix

#32 [Fix] CI/CD Code26
  .github/workflows/Django_CICD.yml
Labels: fix

#36 Feature/login
  allthe/accounts/serializers.py
  allthe/accounts/urls.py
  allthe/accounts/views.py
  allthe/analysis/models.py
  allthe/contents/serializers.py
  allthe/contents/urls.py
  allthe/contents/views.py
Labels: enhancement

#50 find password fixed
  allthe/accounts/migrations/0003_alter_user_nickname.py
  allthe/accounts/models.py
  allthe/accounts/urls.py
  allthe/accounts/views.py
  allthe/allthe/settings.py
Labels: enhancement

#53 [ FIX] 허용 호스트 추가
  allthe/allthe/settings.py
Labels: fix

#54 [FIX]Update settings.py
  allthe/allthe/settings.py
Labels: fix

#52 password confirm added
  allthe/accounts/urls.py
Labels: enhancement

#61 [Feature]ci setting
  .github/workflows/Django_CICD.yml
  .github/workflows/django_ci.yml
Labels: enhancement

#62 [Fix] django ci setting fix 1
  .github/workflows/django_ci.yml
Labels: fix

#63 [Fix] django ci setting fix 2
  .github/workflows/django_ci.yml
Labels: fix

#64 [Fix] django ci setting fix 4
  deploy.sh
  requirements.txt
  wait-for-it.sh
Labels: fix
