Repository OZ-Coding-School/oz_03_collabo-003-BE, pull requests merged in 2024-09, with the labels that each got.

#65 이메일 중복확인 기능 추가
  allthe/accounts/urls.py
  allthe/accounts/views.py
  allthe/contents/views.py
Labels: enhancement

#67 [Fix] CI code
  .github/workflows/django_ci.yml
Labels: fix

#68 [Fix] docekr push error fix(docker-hub env)
  .github/workflows/django_ci.yml
Labels: fix

#69 [FIX] Develop 브랜치도 Docker이미지를 만들수 있도록 수정
  .github/workflows/django_ci.yml
Labels: fix

#70 error code fixed
  allthe/accounts/views.py
Labels: fix

#72 cookie setting
  allthe/accounts/views.py
  allthe/allthe/settings.py
Labels: help wanted

#75 [Fix] Docker build and push in CI
  .github/workflows/django_ci.yml
Labels: fix

#76 [Fix] Docker build and push2
  .github/workflows/django_ci.yml
Labels: fix

#77 [Fix] Docker build and push3 CI Code
  .github/workflows/django_ci.yml
Labels: fix

#78 [Update] Add CD Code
  .github/workflows/django_ci.yml
Labels: enhancement

#79 [Fix] Run Docker-compose with deploy
  .github/workflows/django_ci.yml
Labels: fix

#80 [Fix] Run Docker-compose with deploy
  .github/workflows/django_ci.yml
Labels: fix

#81 [Fix] Run Docker-compose with deploy2
  .github/workflows/django_ci.yml
Labels: fix

#82 [Fix] Run Docker-compose with deploy3
  .github/workflows/django_ci.yml
Labels: fix

#83 [Fix] Run Docker-compose with deploy4
  .github/workflows/django_ci.yml
Labels: fix

#84 [기능 수정] 패스워드 리다이렉트 url 변경
  allthe/accounts/templates/password_reset_email.html
  allthe/accounts/views.py
  allthe/analysis/views.py
  allthe/common/decorators.py
Labels: enhancement

#85 [버그 수정] 패스워드 redirect 버그 수정
  allthe/accounts/views.py
Labels: fix

#90 [버그 수정] 비밀번호 재수정 404 에러 수정
  allthe/accounts/urls.py
  allthe/accounts/views.py
  allthe/allthe/settings.py
  allthe/contents/migrations/0006_content_likes_count_content_views_count_and_more.py
Labels: fix

#93 [버그 수정] 비밀번호 찾기 api 오류 수정
  allthe/accounts/serializers.py
  allthe/accounts/urls.py
  allthe/accounts/views.py
  allthe/contents/migrations/0007_remove_content_likes_count_and_more.py
Labels: fix

#95 [Feat] Add Category Code
  allthe/allthe/settings.py
  allthe/allthe/urls.py
  allthe/category/__init__.py
  allthe/category/admin.py
  allthe/category/apps.py
  allthe/category/migrations/0001_initial.py
  allthe/category/migrations/__init__.py
  allthe/category/models.py
  allthe/category/tests.py
  allthe/category/urls.py
  allthe/category/views.py
Labels: enhancement

#97 [Fix] SWAGGER 테스트를 위한 코드 추가/카테고리 코드 수정
  allthe/accounts/views.py
  allthe/category/serializers.py
  allthe/category/urls.py
  allthe/category/views.py
  allthe/common/decorators.py
Labels: fix

#98 [Fix] 테스트를 위한 데코레이터 임시 제거
  allthe/allthe/settings.py
  allthe/category/views.py
Labels: fix

#105 [Update]Authentications
  allthe/accounts/views.py
  allthe/analysis/views.py
  allthe/contents/views.py
Labels: enhancement

#114 [Feat] 내 정보 조회 추가
  allthe/accounts/views.py
Labels: enhancement

#115 [Fix] Requirements.txt
  requirements.txt
Labels: fix

#116 [Fix] URL 추가
  allthe/accounts/urls.py
Labels: fix

#117 [Fix] 쿠키 인증 설정
  allthe/accounts/ authentication.py
  allthe/allthe/settings.py
Labels: fix

#118 [Fix] django settings.py
  allthe/accounts/authentication.py
Labels: fix

#119 [Fix] Cookie Authentication Setting
  allthe/accounts/authentication.py
  allthe/accounts/views.py
  allthe/analysis/views.py
  allthe/contents/views.py
Labels: fix
